const char *SPLASH_SCREEN = 
"      ..                                                                                            \n"
"    :-=-.           . .:                                                                            \n"
"   :-===:.          .====.                                                                          \n"
"  .==-==--:      .-=*+++:                                                                           \n"
"   -+=====-:   .=+:-+****+.                                                                 :-==-.  \n"
"    :=======:  -**********+                                                            .:=*####*##+ \n"
"      .-===+-. -#*********+                                                         :+*###%%%###**%:\n"
"           .   .+#******##.                                                     :+##*******####%@#. \n"
"      ..-==+=-.  .=*#**+:       ...                                         :+******#####%%%#+:     \n"
"    -+++++*****+-.           ........                                   :=**#*****##%%#*=:.         \n"
"   -+++++*++++++++=:.        ...:::..                               :=*###*#######+=:               \n"
"   +++++++++++++++++++-.      .....         ..                 .:=*#######%##+-.                    \n"
"  :+++****++++++++++===+-              .-++++++*%%%%%%%%#+-:=*####**#%%#+:                          \n"
"   :+****++*+========+**+      .:=*#%#****+*+++++#%%%%%%%%%%####%%#=.                               \n"
"     .=***++***+++++***#+.-=*%*..+%%#*+*+++++***+#%%%%%%%%%%##+:.                                   \n"
"        .-+*****++*****#%%@@@#:..-#%*++++++++****%%%%%%%%%%##-                                      \n"
"         ...:-+*****#%%@@@@%+....+%#++++++++*+**#%%%%%%%%##%#:                                      \n"
"        .... :+%%%%@@@@@%*:....:#%#*++++==+**+*#######%##%%@%-                                      \n"
" ....   ....=%@@@@@%:........=###**+--=+==+***########%%%%%@%-                                      \n"
".:.....-:....*@@@@@%*=---===+##*****++++===+*######%%%%%%@@@%-                                      \n"
" ...:-*@#:....+@@@#=---=====+##*********++++*###%%%%%%%%@@@@%-                                      \n"
"   =%@@@@#:....-+=--=======+*###*********##%%%%%%%%%%%%@@@@@+                                       \n"
"  *%@@@@@@%+..:-======-=:...-*####***##%%%%%%%%%%%%%%%@@@@%-                                        \n"
" .%@@@@@@@@%%#*--==---==:::::=*##%%%%%%%%%%%%%%%%%%%@@@@%:                                          \n"
"  :#%%%@@@%#####*+=++***###%%%%%%%%%%%%%%%%%%%%%%%@@@@+.                                            \n"
"   .*##########%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@@%*:                                               \n"
"     +#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+:                                                  \n"
"      -#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+:                                                      \n"
"       :#%%%%%%%%%%%%%%%%%%%%%%%%%%%@%#+:                                                           \n"
"         =#%%%%%%%%%%%%%%%%@@@%#*+-.                                                                \n"
"           .:-=+***#**+==-::.                                                                       \n"
"                                                                                                    \n"
"                                                                                                    \n"
"     Welcome to Dinner Bash : A CLI Cooking Management Game                                         \n"
"     Made by Addin Munawwar Yusuf ( Cadevue )                                                       \n"
"     C Programming  ||  Algorithm and Data Structure                                                \n"
"                                                                                                    \n"
"                                                                                                    \n"
"     Press enter to continue . . .                                                                  \n"
;


const char * HEADER=
"Dinner Bash : A Cooking Management CLI Simulation                                                   \n"
"Made by Addin Munawwar Yusuf ( Cadevue )                                                            \n"
"C Programming  ||  Algorithm and Data Structure                                                     \n"
"                                                                                                    \n"
;

const char * HELP_COMMANDS=
">-------------------------------------------------------<\n"
"|=======================COMMANDS========================|\n"
"| All the commands are case-insensitive.                |\n"
"|                                                       |\n"
"| \033[1mGeneral\033[0m:                                              |\n"
"|   - help     : Display all available commands.        |\n"
"|   - exit     : Exit the game.                         |\n"
"|   - wait h m : Wait for h hours and m minutes.        |\n"
"|                                                       |\n"
"| \033[1mNavigation\033[0m:                                           |\n"
"|   - up       : Move upwards.                          |\n"
"|   - down     : Move downwards.                        |\n"
"|   - left     : Move to the left.                      |\n"
"|   - right    : Move to the right.                     |\n"
"|                                                       |\n"
"| All navigation command can be shortened to 'u', 'd',  |\n"
"| 'l', and 'r' respectively.                            |\n"
"|                                                       |\n"
"| \033[1mCooking\033[0m:                                              |\n"
"| All the cooking commands must be done in the adjacent |\n"
"| to its action tile.                                   |\n"
"|                                                       |\n"
"| (e.g. 'buy' can only be done if the player adjacent   |\n"
"| to the telephone (T) tile)                            |\n"
"|                                                       |\n"
"|   - buy      : Buy ingredients (T).                   |\n"
"|   - mix      : Mix ingredients (M).                   |\n"
"|   - chop     : Chop ingredients (C).                  |\n"
"|   - fry      : Fry ingredients (F).                   |\n"
"|   - boil     : Boil ingredients (B).                  |\n"
"|                                                       |\n"
"| \033[1mInfo\033[0m:                                                 |\n"
"|   - legend   : Display the map legend.                |\n"
"|   - inventory: Display the player's inventory.        |\n"
"|   - delivery : Display all ongoing deliveries.        |\n"
"|   - catalog  : Display the catalog of food &          |\n"
"|                ingredients.                           |\n"
"|   - cookbook  : Display all available recipes.        |\n"
"|                                                       |\n"
"| type 'back' to return to the game.                    |\n"
"<------------------------------------------------------->\n\n"
;

const char * LEGEND=
">-------------------------------------------------------<\n"
"|=======================LEGEND==========================|\n"
"|                                                       |\n"
"| \033[1;31m@\033[0m: Player.                                            |\n"
"| \033[1;30mX\033[0m: Wall.                                              |\n"
"| \033[1;32mT\033[0m: Telephone.                                         |\n"
"| \033[1;32mM\033[0m: Mixer.                                             |\n"
"| \033[1;32mC\033[0m: Chopper.                                           |\n"
"| \033[1;32mF\033[0m: Frying Pan.                                        |\n"
"| \033[1;32mB\033[0m: Boiling Pot.                                       |\n"
"| * : Border.                                           |\n"
"|                                                       |\n"
"| type 'back' to return to the game.                    |\n"
"<------------------------------------------------------->\n\n"
;